# Generated by Django 2.0 on 2018-08-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20180815_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author',
        ),
    ]
