# Generated by Django 2.0 on 2018-08-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_author_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='checked_out_to_whom',
            field=models.CharField(default ="", max_length=250),
        ),
    ]
