# Generated by Django 2.0 on 2018-08-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20180819_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checked_out_to_whom',
            field=models.CharField(max_length=250),
        ),
    ]
