# Generated by Django 2.0 on 2018-08-20 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_auto_20180819_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='checked_out',
        ),
        migrations.AddField(
            model_name='book',
            name='checked_out_when',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 4, 27, 8, 875842)),
        ),
    ]
